# @link https://docs.vagrantup.com.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "../.", "/server-setup"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.box_check_update = false
end
